// src/pages/About.jsx
import React from "react";
import { pickAsset } from "../components/AssetPicker.js";

const heroImg = pickAsset(["about-hero", "team", "mission", "forest", "mountain"]);
const missionImg = pickAsset(["mission", "vision", "earth"]);
const impactImg = pickAsset(["impact", "stats", "climate"]);
const teamImgs = [
  pickAsset(["team1","member1","avatar1","profile1"]),
  pickAsset(["team2","member2","avatar2","profile2"]),
  pickAsset(["team3","member3","avatar3","profile3"]),
  pickAsset(["team4","member4","avatar4","profile4"]),
].filter(Boolean);

const impacts = [
  { label: "Trees Planted", value: "48,200" },
  { label: "kWh Reduced", value: "1.2M" },
  { label: "CO₂ Avoided (kg)", value: "560K" },
  { label: "Active Users", value: "4,210" },
];

export default function About() {
  return (
    <div className="space-y-10">
      {/* Hero */}
      <section className="rounded-3xl overflow-hidden border border-emerald-100 bg-white">
        <div className="relative h-64">
          {heroImg ? (
            <img src={heroImg} alt="About Hero" className="absolute inset-0 w-full h-full object-cover" />
          ) : (
            <div className="absolute inset-0 hero-gradient" />
          )}
          <div className="absolute inset-0 bg-emerald-900/40" />
          <div className="relative z-10 h-full flex flex-col justify-center px-8">
            <h1 className="text-4xl font-extrabold text-white">Our Mission & Vision</h1>
            <p className="mt-3 max-w-xl text-emerald-50 text-sm">
              Empower individuals and communities to measure, understand, and reduce their environmental impact.
            </p>
          </div>
        </div>
      </section>

      {/* Mission & Vision */}
      <section className="grid md:grid-cols-2 gap-8">
        <div className="rounded-2xl bg-white border border-emerald-100 p-6">
          <h2 className="text-xl font-semibold text-emerald-800 mb-3">Mission</h2>
          <p className="text-sm text-emerald-900/80">
            Provide accessible tools for tracking energy usage and carbon emissions, driving informed sustainable decisions.
          </p>
          <h2 className="text-xl font-semibold text-emerald-800 mt-6 mb-3">Vision</h2>
          <p className="text-sm text-emerald-900/80">
            A global network collaboratively reducing ecological footprints and accelerating climate-positive projects.
          </p>
        </div>
        <div className="rounded-2xl bg-white border border-emerald-100 p-0 overflow-hidden">
          {missionImg ? (
            <img src={missionImg} alt="Mission" className="w-full h-full object-cover" />
          ) : (
            <div className="h-full hero-gradient min-h-[260px]" />
          )}
        </div>
      </section>

      {/* Impact Stats */}
      <section className="rounded-3xl bg-white border border-emerald-100 p-8">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 mb-8">
          <div>
            <h2 className="text-2xl font-bold text-emerald-800">Impact Snapshot</h2>
            <p className="text-sm text-emerald-900/80 mt-2">
              Real results generated by our growing community of sustainable actors.
            </p>
          </div>
          <div className="w-48 h-32 rounded-xl overflow-hidden border border-emerald-100">
            {impactImg ? (
              <img src={impactImg} alt="Impact" className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full hero-gradient" />
            )}
          </div>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {impacts.map(i => (
            <div key={i.label} className="rounded-xl bg-emerald-50 border border-emerald-100 p-4">
              <p className="text-xs font-semibold text-emerald-700">{i.label}</p>
              <p className="text-xl font-extrabold text-emerald-900 mt-1">{i.value}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Team */}
      <section className="rounded-3xl bg-white border border-emerald-100 p-8">
        <h2 className="text-2xl font-bold text-emerald-800 mb-6">Meet the Team</h2>
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-6">
          {(teamImgs.length ? teamImgs : [null, null, null, null]).map((src, idx) => (
            <div key={idx} className="rounded-xl border border-emerald-100 p-5 bg-emerald-50 flex flex-col items-center text-center">
              <div className="w-24 h-24 rounded-full overflow-hidden mb-3 border border-emerald-100 bg-emerald-200">
                {src ? <img src={src} alt={`Team member ${idx+1}`} className="w-full h-full object-cover" /> : null}
              </div>
              <p className="text-sm font-semibold text-emerald-800">Member {idx + 1}</p>
              <p className="text-xs text-emerald-900/70 mt-1">Sustainability</p>
            </div>
          ))}
        </div>
      </section>

      {/* Stories */}
      <section className="rounded-3xl bg-white border border-emerald-100 p-8">
        <h2 className="text-2xl font-bold text-emerald-800 mb-4">Impact Stories</h2>
        <div className="space-y-4">
          <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 text-sm text-emerald-900/80">
            A local school reduced its yearly energy use by 32% after adopting weekly tracking dashboards.
          </div>
          <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 text-sm text-emerald-900/80">
            Community solar project participants collectively offset thousands of kilograms of emissions.
          </div>
          <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 text-sm text-emerald-900/80">
            Household monitoring guided smarter appliance usage and peak-time avoidance strategies.
          </div>
        </div>
      </section>
    </div>
  );
}
